#! /bin/bash

#cat nowiki-20151020-pages-articles.xml | ../../dotno-ml > nowiki.dom.first;

cat nowiki.dom.first | tr 'A-Z' 'a-z' | sort | uniq > nowiki.dom.1 

while read LINE; 
do
        F=$(idn $LINE >> nowiki.dom.2);
        if [ $? -gt 0 ]; then
                echo error $LINE >> nowiki.dom.idnerror;
        fi;
done  <<<"$(cat nowiki.dom.1)"


cat nowiki.dom.2 | tr 'A-Z' 'a-z' | sort | uniq > nowiki.domains
rm nowiki.dom.1 nowiki.dom.2
